# Generated by Django 3.0.6 on 2020-05-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sruser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('useremail', models.EmailField(max_length=128)),
                ('password', models.CharField(max_length=64)),
                ('registered_dttm', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
